package P_20211223.exception3;

import java.util.Scanner;

public class String03P399 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("문장을 입력해주세요");
		String string = sc.next();

		System.out.println("찾으려는 단어를 입력해주세요");

		String find = sc.next();
		int counting = 0;
		int index = 0;

		int finding = string.indexOf(find,index+1);
		System.out.println(finding);
		string = string.substring(finding+1);
		finding = string.indexOf(find,index+1);
		System.out.println(finding);
		string = string.substring(finding+1);
		finding = string.indexOf(find,index+1);
		System.out.println(finding);
		string = string.substring(finding+1);
		finding = string.indexOf(find,index+1);
		System.out.println(finding);
		string = string.substring(finding+1);
		finding = string.indexOf(find,index+1);
		System.out.println(finding);
		string = string.substring(finding+1);
		
		
		try {

			while(index < 0 ) {
				
				if(finding == -1) {
					System.out.println("단어가 없습니다.");
					break;
				}else {
					counting++;
					System.out.println(counting+"번째 단어는" + 
					finding + "번째에 있습니다.");
				}
			}
		}
		catch(Exception e) {
			System.out.println(e);
		}
	}
}
