package P_20211222.exception01;

import java.util.Scanner;

public class Exception03P348 {
	public static void main(String[] args) {
		//예외발생 케이스 3
		Scanner s = null;
		s.close();
	}
}
